name: Deploy Test Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env File
        run: echo "PORT= ${{ secrets.PORT }}" >> .env
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/go-app .
      - name: Push Docker Image
        run: docker push brainzcode/go-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull brainzcode/go-app:latest
      - name: Stop and Remove Docker Container
        run: docker stop go-app-container && docker rm go-app-container || true
      - name: Run Docker Container
        run: docker run -d -p 9090:9090 --name go-app-container brainzcode/go-app